### ISSUE TITLE
Will you categorize and organize those report file by continent or country?

### ISSUE THREAD

**Issue by LaoshuBaby** [matkoniecz/OSM-wikipedia-tag-validator-reports#1]
There are 975 file in root dictionary and without any folder, only a address prefix, and if users want to find a region-specific report, they have to get trouble to find it. 

Another question is, looks like current analysis is limited to Europe and America, with a very few Asian countries? Will a focus on East Asia and Africa be provided in the future?

**Comment by matkoniecz** [comment]
> Another question is, looks like current analysis is limited to Europe and America, with a very few Asian countries? Will a focus on East Asia and Africa be provided in the future?

Are you interested in fixing issues in some specific country on area? As mentioned on website, I can add more regions if someone is interested

> There are 975 file in root dictionary and without any folder, only a address prefix, and if users want to find a region-specific report, they have to get trouble to find it.

this only exists as hosting repo, users are expected to use https://matkoniecz.github.io/OSM-wikipedia-tag-validator-reports/ website. Is it good enough?

**Comment by LaoshuBaby** [comment]
> this only exists as hosting repo, users are expected to use https://matkoniecz.github.io/OSM-wikipedia-tag-validator-reports/ website. Is it good enough?

Sorry, I'm thinking too much

> Are you interested in fixing issues in some specific country on area? As mentioned on website, I can add more regions if someone is interested

Yes, I can only feel that the data quality in China is terrible, but I don't know how many problems there are and where. It is best if it can be provided in provincial level report. If it is inconvenient, a whole country report in one file is also very useful

**Comment by matkoniecz** [comment]
@LaoshuBaby https://matkoniecz.github.io/OSM-wikipedia-tag-validator-reports/ is now providing reports for China

I will enable more provinces as errors will get fixed, feel free to ping me (or even better - open a new issue or send PM at OSM) if I will miss it

Feel free to open a new issue if there will be need for more countries, specific province or any reported issues will be bogus/unclear/outdated
